### ISSUE TITLE
Auswerten-Baustein für Tages-Max der PV-Anlage

### ISSUE THREAD

**Issue by jaydee73** [Sleepwalker86/SMo-Gira-X1-Logic-Nodes#1]
Hi!

Ich bin über den Smarthome-Appstore auf deinen Baustein "Auswerten" aufmerksam geworden. Vielleicht ist mein Anliegen gar kein richtiges Issue, aber da es in diesem Repo kein Discussions-Tab gibt, versuche ich es mal hier. ;-)

Folgende Situation bei mir: Alle 30sek. fragt ein anderer Baustein die Daten meines Wechselrichters ab, u. a. den aktuellen Ertrag in Watt. Ich möchte deinen Auswerten-Baustein nun gerne dafür nutzen, das Tagesmaximum zu ermitteln und an den Ausgang zu geben. Bin mir aber nicht ganz sicher, ob ich deine Parameter richtig interpretiere und ob der Baustein dafür überhaupt aktuell geeignet ist.

Ich gebe als Parameter Max und als Reset habe ich eine Zeitschaltuhr, welche jede Nacht um 00:01 Uhr triggert. Das funktioniert auch. Als Anzahl Werte habe ich aktuell 2, aber das scheint nicht zu funktionieren. Nach zwei erfassten Werten fängt der Baustein quasi wieder vorne an. Maximal kann ich aber nur 500 angeben, und bei 24 Stunden und 2x pro Minute abfragen komme ich halt auf mehr als 500 Werte.

Eigentlich müsste ich ja nur den jeweils reinkommenden Wert mit dem zuletzt gespeicherten Max-Wert vergleichen. Wenn kleiner, bleibt der Max-Wert. Wenn größer, wird ein neuer Max-Wert gesetzt. So in der Art... ;-) Deswegen dachte ich, dass "Anzahl Werte 2" hier richtig wäre.

Könntest du mir da mal ein Feedback geben, ob mein Anliegen mit deinem Baustein umsetzbar ist und wenn ja, was ich falsch gemacht habe? 

Dank dir,
Stefan

**Comment by Sleepwalker86** [comment]
Hallo Stefan, danke für dein Feedback. Du hast recht für deinen Fall funktioniert er aktuell nicht aufgrund der maximalen Anzahl an Werten von 500. Der Parameter maximaler Wert bedeutet das der Baustein nach dem erreichen dieses Wertes zurück gesetzt wird. Damit will ich verhindern das der Speicher von x1 voll läuft. Diesen Wert hatte ich letztens angehoben da ich davon ausgehe das er diese Anzahl problemlos schafft. Wenn ich aus dem Urlaub zurück bin könnte ich den Wert erhöhen und dir zum Testen zur Verfügung stellen. Wenn du mir dann keine Probleme zurück meldest und den Speicher von X1 im Auge behältst könnte ich eine neue Version öffentlich machen. Ich habe den Baustein ursprünglich nur zum verdichten von Daten entwickelt, das mit den min und Max werten kam später dazu da es einfach zu implementieren war. Ich verwende im Baustein eine Standard Funktion eines Frameworks und diese Funktion wird mathematisch von allen werten berechnet. Er überschreibt nicht den letzten wenn der neue höher ist. Mit freundlichen Grüßen Sascha MoritzAm 20.05.2024 um 16:45 schrieb jaydee73 ***@***.***>:﻿
Hi!
Ich bin über den Smarthome-Appstore auf deinen Baustein "Auswerten" aufmerksam geworden. Vielleicht ist mein Anliegen gar kein richtiges Issue, aber da es in diesem Repo kein Discussions-Tab gibt, versuche ich es mal hier. ;-)
Folgende Situation bei mir: Alle 30sek. fragt ein anderer Baustein die Daten meines Wechselrichters ab, u. a. den aktuellen Ertrag in Watt. Ich möchte deinen Auswerten-Baustein nun gerne dafür nutzen, das Tagesmaximum zu ermitteln und an den Ausgang zu geben. Bin mir aber nicht ganz sicher, ob ich deine Parameter richtig interpretiere und ob der Baustein dafür überhaupt aktuell geeignet ist.
Ich gebe als Parameter Max und als Reset habe ich eine Zeitschaltuhr, welche jede Nacht um 00:01 Uhr triggert. Das funktioniert auch. Als Anzahl Werte habe ich aktuell 2, aber das scheint nicht zu funktionieren. Nach zwei erfassten Werten fängt der Baustein quasi wieder vorne an. Maximal kann ich aber nur 500 angeben, und bei 24 Stunden und 2x pro Minute abfragen komme ich halt auf mehr als 500 Werte.
Eigentlich müsste ich ja nur den jeweils reinkommenden Wert mit dem zuletzt gespeicherten Max-Wert vergleichen. Wenn kleiner, bleibt der Max-Wert. Wenn größer, wird ein neuer Max-Wert gesetzt. So in der Art... ;-) Deswegen dachte ich, dass "Anzahl Werte 2" hier richtig wäre.
Könntest du mir da mal ein Feedback geben, ob mein Anliegen mit deinem Baustein umsetzbar ist und wenn ja, was ich falsch gemacht habe?
Dank dir,
Stefan

**Comment by jaydee73** [comment]
Hi,
also ich teste gerne. Du könntest natürlich auch theoretisch noch die SD-Card zur Datenablage nutzen. Dann hättest du vermutlich gar kein Problem mit dem Speicherplatz. Aber ebenso vermute ich, dass das einen größeren Umbau des Bausteins bedingen würde... ;-)

**Comment by Sleepwalker86** [comment]
ich habe den Baustein geändert. Du kannst ihn gerne testen.

**Comment by jaydee73** [comment]
Dank dir. Bin die nächsten drei Tage beruflich unterwegs. Kann daher erst am Wochenende testen. 

Und ich habe nochmal überlegt: statt bisher max 500 Werte habe ich ja dann knapp 3000 Werte pro Tag. Siehst du da ein Problem? Die bisherige Begrenzung auf 500 hatte ja vielleicht einen Grund?! 😳

Und könntest du mir noch helfen, wo genau ich schauen soll, ob der x1 vollläuft? Vermutlich ja auf der Diagnose-Seite? Aber wo genau? RAM? Oder gibt es für einzelne LBS eine dedizierte Übersicht der Ressourcen?

Und nach meinem Verständnis müsste der RAM-Bedarf im Verlauf des Tages steigen und dann um Mitternacht wieder runter gehen, wenn der Zeittrigger kommt. Oder allokiert der LBS direkt den gesamten Bedarf für den maximal benötigten Speicher?

**Comment by Sleepwalker86** [comment]
Ich habe den Max Wert jetzt auf 3000 gesetzt. Ich habe mir das mal berechnet und eigentlich dürfte der ram nicht spürbar steigen da 3000 werte nur 90kb groß sind. Sollte eigentlich kein Problem sein. 
Du kannst es auf der Diagnose Seite sehen oder im GPA bei der Übersicht der Logiken. 

Die 500 hatten den Grund das ich nicht wollte das mein Baustein Probleme machen könnte. Aber jetzt wo ich das berechnet habe gehe ich davon aus das es problemlos möglich ist.

**Comment by jaydee73** [comment]
Ok, gut zu wissen. Andere Frage: Die 1.1.5 hat einen minimal anderen Namen als die 1.1.3. Erkennt der GPA, dass das eine neuere Version eines bestehenden Bausteins ist? Oder wird die 1.1.5 als weiterer Baustein angesehen?

![grafik](https://github.com/Sleepwalker86/SMo-Gira-X1-Logic-Nodes/assets/21342601/76619654-9d5c-45b8-9520-b4dae08c0e40)

**Comment by Sleepwalker86** [comment]
Er wird erkennen das es der selbe ist. Und du musst die Logikbausteibe aktualisieren. Der Name wurde vom App Shop geändert. Spielt aber keine Rolle

**Comment by jaydee73** [comment]
Kurzes Update: Ich habe den Baustein gestern eingespielt. Zunächst lief alles "normal", aber heute früh wurden die Logiken nicht mehr komplett ausgeführt. Auch nach einem Restart nicht mehr.

Das muss aber nicht zwangsweise an deinem Baustein liegen. Ich habe zum Einen noch einen weiteren Baustein mit hinzugenommen und außerdem habe ich nachträglich dann festgestellt, dass eine Webseite, die ich via Request regelmäßig abfrage, derzeit offline ist. Auch das hat irgendwie zu Schluckauf am X1 geführt. Das betreffende Logikblatt habe ich nun zunächst deaktiviert und deinen Baustein erstmal wieder rausgenommen. Nun geht wieder alles andere.

Ich werde nun zunächst mal abwarten, bis die Webseite wieder erreichbar ist. Danach werde ich nochmal neu testen.

**Comment by jaydee73** [comment]
So, nun läuft der Baustein. Aktuell wurde heute schon 2000 Werte gespeichert. Keine nennenswerten Veränderungen bei Memory/Memory free/CPU Load. Der Reset um Mitternacht klappt auch, das hatte ich letzte Nacht schon gesehen.

Insofern alles schick.

**Comment by Sleepwalker86** [comment]
Top sehr gut. Danke fürs Feedback. Wenn alles klappt werde ich den Baustein im Appshop auch austauschen.

**Comment by jaydee73** [comment]
Nach einem weiteren Tag schaut weiterhin alles gut aus. Für mich wäre der Test damit erfolgreich abgeschlossen. ;-)
