### ISSUE TITLE
Sirene stoppen

### ISSUE THREAD

**Issue by PhilW35** [Sleepwalker86/SMo-Gira-X1-Logic-Nodes#3]
Hi Sascha, wäre es möglich die Sirene nach Alarmauslösung nach 180s zu stoppen und dann nach 1 Minute wieder scharf zu schalten damit bei weiterer Auslösung die Sirene wieder losgehen kann. Damit würde das dann auch schon fast VDE konform sein. Das Blitzlicht kann ja weiter blitzen.
Die Kür wär natürlich wenn das einstellbar wäre.
Ich kann natürlich auch Zeitbausteine dahinter packen, cool wär aber wenn das alles schon drin wäre

Gruss

Guido

**Comment by Sleepwalker86** [comment]
Hallo Guido,
Danke für die Rückmeldung. Ich schaue mir das gerne an ob und wie ich das umsetze.
Gruß Sascha

**Comment by PhilW35** [comment]
Vielen Dank, das wäre wirklich cool.
So einfach kann ich das mit X1 Boardmitteln gar nicht lösen. Ich kann zwar die Sirene mit Treppenhausbaustein begrenzen aber nicht wieder (ohne einen manuellen Eingriff) zum Leben erwecken bzw wieder scharf schalten da sie ja vermeindlich scharf (1) ist.

Gruss
Guido

**Comment by Sleepwalker86** [comment]
Anpassung wurde mit Commit 243562c vorgenommen
Version 1.2.0
